### ISSUE TITLE
Invalid lido:lidoWrap placement

### ISSUE THREAD

**Issue by klindt** [M-DS0002/Normdatenfokussierter_Beispieldatensatz#1]
lido:lidoWrap inside lido:lido element is not allowed. Use lido:Wrap only as wrapper for (multiple) lido:lido elements.

**Comment by M-DS0002** [comment]
Den <lidoWrap> wollte ich ursprünglich gar nicht einbauen, da dies das Zusammenfügen von Lido-Dateien behindert. Allerdings dokumentieren wir <lidoWrap> nun mal in DDB-Lido, daher habe ich den Wrapper nun doch eingebaut (bin aber wohl in der Zeile verrutscht).

**Comment by M-DS0002** [comment]
Müsste jetzt passen.
