### ISSUE TITLE
Typo in URI

### ISSUE THREAD

**Issue by klindt** [M-DS0002/Normdatenfokussierter_Beispieldatensatz#2]
https://github.com/M-DS0002/Normdatenfokussierter_Beispieldatensatz/blob/cccd2d587cf1f330ab1fd945454f76166862b59f/Beispieldatensatz_Beta_XML#L71

Should be "http://vocab.getty.edu/aat/300435416"

**Comment by M-DS0002** [comment]
Danke, korrigiert
